### ISSUE TITLE
 Cobra-Cli init Error

### ISSUE THREAD

**Issue by aleite31** [spf13/cobra-cli#31] opened 2022-04-14 13:23 UTC
Error using "cobra-cli ini" --> Error: invalid character '{' after top-level value

Go version : 1.18.1
VsCode : 1.66.1

**Comment by tahsinrahman** [comment] 2022-05-16 01:15
i'm having the same issue 

go version 1.18.1

**Comment by angelorc** [comment] 2022-05-27 22:47
same here, the issue appear if you use `go work`

**Comment by kcmvp** [comment] 2022-06-11 09:24
> i'm having the same issue
> 
> go version 1.18.1
> 
> update: seems it only occurs with go.work. #26

yes, my project is in a workspace

**Comment by fseesink** [comment] 2022-06-18 02:53
I am experiencing the same with Go 1.18.3 on macOS 12.4 "Monterey".  And like the others, I, too, am in Go workspace.

If instead, at my Desktop or just a directory that's not a Go workspace, I simply
1. mkdir Test
2. cd Test
3. go mod init cobratest
4. cobra-cli init

then all is well.

So there definitely seems to be something with regard to the Go workspace feature for some reason.

**Comment by tomato-ga** [comment] 2022-06-22 11:05
I am running into a similar problem with init.

~/go/src/cobra  cobra-cli init
cobra-cli: command not found

Installation is done
<img width="978" alt="スクリーンショット 2022-06-22 20 04 29" src="https://user-images.githubusercontent.com/52771764/175014177-5dc4b2da-3733-4489-893a-e5fce2d2ffed.png">

**Comment by marckhouzam** [comment] 2022-06-22 13:25
> I am running into a similar problem with init.
> 
> ~/go/src/cobra cobra-cli init cobra-cli: command not found

Try `./cobra-cli init`

**Comment by tomato-ga** [comment] 2022-06-22 13:47
@marckhouzam 

Thx!
It didn't seem to work because I was running it in a VS code terminal, 
I tried it with an SSH connection and it worked.

<img width="323" alt="スクリーンショット 2022-06-22 22 45 53" src="https://user-images.githubusercontent.com/52771764/175044821-d55310c4-624c-488b-9636-a926e382c5aa.png">

**Comment by DevolvingSpud** [comment] 2022-07-04 16:01
Seeing the same issue here, first module worked, second is unhappy in exactly the same way as the above.

I worked around it by doing the `init` in a directory not under the workspace, then copying everything in.  Once that's in place, the other commands (`add` etc.) seem to work.

**Comment by ezk84** [comment] 2022-08-22 18:42
Running into this also, and also using a workspace. Followed @DevolvingSpud's workaround for now.

**Comment by ebarti** [comment] 2022-09-16 19:30
Same here, go workspaces are quite a disappointing feature to be honest, they seem to create more issues than anything.

**Comment by marckhouzam** [comment] 2022-09-19 01:44
When doing an `init`, the `cobra-cli` runs `go list -json -m` to get information about the current module.
When using go workspaces, that command returns all modules in the workspace, which looks something like this:
```
$ go list -json -m
{
	"Path": "github.com/marckhouzam/cli",
	"Main": true,
	"Dir": "/Users/kmarc/tmp/cli",
	"GoMod": "/Users/kmarc/tmp/cli/go.mod",
	"GoVersion": "1.18"
}
{
	"Path": "github.com/marckhouzam/cli2",
	"Main": true,
	"Dir": "/Users/kmarc/tmp/cli2",
	"GoMod": "/Users/kmarc/tmp/cli2/go.mod",
	"GoVersion": "1.18"
}
```
This a a case the `cobra-cli` is not handling.  We need to handle workspaces properly.

**Comment by marckhouzam** [comment] 2022-09-19 01:50
Duplicate of #26

**Closed by marckhouzam** 2022-09-19 01:50 UTC
